#!/bin/bash
# REV02: Wed Feb  6 19:20:23 WIB 2019
# REV01: Thu Jan 17 11:17:05 WIB 2019
# START: Xxx Xxx XX XX:XX:XX XXX 2018
#
# Copyright (C) 2018-2019 Rahmat M. Samik-Ibrahim
# http://RahmatM.Samik-Ibrahim.vLSM.org/
# This program is free script/software. This program is distributed in the hope 
# that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# R: UTS 2018-1 (midterm)

echo "START"
for II in "SATU DUA TIGA"
do echo $II ; done
for II in SATU DUA TIGA
do echo $II ; done
echo "STOP"

