#!/bin/bash
# REV01: Thu Jan 17 11:20:35 WIB 2019
# START: Mon Mar 24 21:00:00
# 
# Copyright (C) 2019 Rahmat M. Samik-Ibrahim
# http://RahmatM.Samik-Ibrahim.vLSM.org/
# This program is free script/software. This program is distributed in the hope 
# that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

TIGA=3
ANGKA="1 2 \$TIGA"
echo "START"
echo "ANGKA"
echo "$ANGKA"
echo "$ANGKA" | gawk '/TIGA/ {print $1, $2}'
echo "STOP"
