# (c) 2016-2019 Rahmat M. Samik-Ibrahim
# REV02 Fri Jan 25 18:57:28 WIB 2019
# REV01 Tue Aug 22 14:45:14 WIB 2017
# START Fri Jan 01 00:00:00 WIB 2016
# This is a free Makefile configuration.
# Just run:
# % make

ALL:	c-program-example

c-program-example: c-program-example.c
	gcc -o c-program-example c-program-example.c

.phony: ALL clean

clean:
	rm -f c-program-example

